Feat: 푸터 웹 컴포넌트
FRONTENDSCHOOL10/ssagwa-kurly pull request #16
Opened 2024-07-06 10:24 UTC by chlyun

## 🔧 반영 브랜치

feat/component-footer -> develop

## 💬 Description

SNS 링크 연결
메일 링크 클릭시 메일 앱 연결
인증정보페이지 연결
전화번호 연결
문의 버튼 클릭시 연결

## 📷 Screenshots
![image](https://github.com/FRONTENDSCHOOL10/ssagwa-kurly/assets/119630708/9ed848dd-7829-4e4b-afd7-35b631f6a95d)

2024-07-06 12:35 UTC, jaehwan-space requested changes
# PR 리뷰
## 요약
- JavaScript 클래스 이름 규칙: PascalCase 사용
- HTML 클래스 이름 규칙: 소문자와 하이픈 사용
- footer 컴포넌트 폴더의 HTML 파일명을 index.html로 변경 요청
- HTML 문법 검사 시 link 태그의 폰트 가져오는 부분에서 오류 발생
## 피드백
1. JavaScript 클래스 이름 규칙

   - JavaScript 클래스 이름은 PascalCase를 사용해야 합니다.
   - 예시: class FooterComponent { ... }
    ```javascript
    class FooterComponent {
        // 클래스 내용
    }
    ```
2. HTML 클래스 이름 규칙

    - HTML 클래스 이름은 소문자와 하이픈을 사용하여 작성해야 합니다.
    - 예시: <div class="footer-container"></div>
    ````html
    <div class="footer-container">
        <!-- HTML 내용 -->
    </div>
    ````
3. 파일명 변경 요청

    - footer 컴포넌트 폴더의 HTML 파일명을 index.html로 변경해 주세요.
    - 예시:
    ````css
    footer/
    └── index.html
    ````
4. HTML 문법 검사 오류 수정

    - link 태그에서 폰트를 가져오는 부분에서 오류가 발생하고 있습니다.
    - as="style"을 사용할 때 rel 속성에 preload를 포함해야 합니다.
    - 수정 방법:
    ````html
    <!-- 미리 로드 -->
    <link rel="preload" as="style" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css" />
    <!-- 스타일시트 적용 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css" />
    ````
## 수정 후 코드 예시
````javascript
// JavaScript 클래스 이름 (PascalCase 사용)
class FooterComponent {
    // 클래스 내용
}
````
````html
<!-- HTML 클래스 이름 (소문자와 하이픈 사용) -->
<div class="footer-container">
    <!-- HTML 내용 -->
</div>

<!-- HTML 파일명 변경 (footer/index.html) -->
<!-- HTML 문법 검사 오류 수정 -->
<link rel="preload" as="style" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css" />
````
## 최종 평가
위의 수정 사항들을 반영해주시면, 코드의 일관성과 HTML 문법 검사를 통과할 수 있습니다. 변경 사항을 반영해 주시면 PR을 승인하겠습니다. 감사합니다!

승인 상태: 수정 요청

2024-07-08 05:31 UTC, jaehwan-space approved these changes

2024-07-08 05:41 UTC, jaehwan-space submitted a review, later dismissed
# PR 리뷰
## 요약
- vite.config.js에서 footer 빌드를 제외
- index.html의 타이틀을 "Component - Footer"로 변경
- CSS 클래스 이름 규칙을 BEM 방식으로 사용
## 피드백
1. vite.config.js 수정

    - components는 빌드가 필요 없으므로 footer를 빌드에서 제외해 주세요.
    - 예시:
    ```javascript
    // vite.config.js
    rollupOptions: {
      input: {
        main: resolve(root, 'index.html'),
        // footer 제외
      },
    },
    ```
2. index.html 타이틀 변경

    - index.html의 타이틀을 "Component - Footer"로 변경해 주세요.

3. CSS 클래스 이름 규칙 (BEM 방식)

    - CSS 클래스 이름 규칙을 BEM(Block, Element, Modifier) 방식으로 사용해 주세요.
    - 예시:
      ```css
      /* BEM 방식으로 클래스 이름 수정 */
      .button-group {
        margin-top: 1rem;
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
        align-items: center;
      }

      .button-group__button {
        width: 21.25rem;
        height: 3.375rem;
        border-radius: 0.25rem;
        border: 1px solid var(--color-button, #5F0080);
        font-size: 1rem;
      }

      .button-group__button--white {
        background-color: white;
        color: var(--color-button, #5F0080);
      }
      ```

## 최종 평가
위의 수정 사항들을 반영해주시면, 코드의 일관성과 유지보수성이 향상될 것입니다. 변경 사항을 반영해 주시면 PR을 승인하겠습니다. 감사합니다!

승인 상태: 수정 요청

2024-07-11 01:09 UTC, dabini99 approved these changes
검토 했습니다!

2024-07-11 01:12 UTC, merged