Feat: 버튼 컴포넌트 구현
FRONTENDSCHOOL10/ssagwa-kurly pull request #17
Opened 2024-07-06 11:51 UTC by dabini99

## 🔧 반영 브랜치
---

feat/component-button -> develop 

## 💬 Description
---

버튼 컴포넌트 제작

## 📷 Screenshots
---
<img width="355" alt="스크린샷 2024-07-06 오후 8 50 34" src="https://github.com/FRONTENDSCHOOL10/ssagwa-kurly/assets/150096256/9f96cd0f-8f55-414d-8743-d99192e48e95">

Resolves #1

2024-07-08 05:29 UTC, jaehwan-space requested changes
# PR 리뷰
## 요약
- 컬러 변수는 공통 스타일(global.css)에서 가져와서 사용 필요
- 중복된 CSS 코드를 하나의 클래스로 통일
- <head> 태그 규칙

## 피드백
1. 컬러 변수의 사용

    - 컬러 변수를 공통 스타일(global.css)에서 가져와서 사용해 주세요. 이를 통해 일관성을 유지하고, 유지보수를 용이하게 할 수 있습니다.
    - 예시:
    ```css
    /* global.css */
    :root {
        --primary: #e23e57;
      --content: #333333;
      --black: #000000;
      --white: #ffffff;
      --gray-50: #f9f9f9;
    }
    ```
2. 중복된 CSS 코드 통일

    - 중복된 CSS 코드를 하나의 클래스로 통일시키는 것이 좋습니다.
    - 예시:
    ```css
    /* button.css */
    .button {
      width: 21.25rem;
      height: 3.375rem;
      border-radius: 0.25rem;
      border: 1px solid var(--color-button, #5F0080);
      font-size: 1rem;
    }

    .button--white {
      background-color: white;
      color: var(--color-button, #5F0080);
    }

    .button--purple {
      background-color: var(--color-button, #5F0080);
      color: white;
    }
    ```

3. HTML 문서에 `<head>` 태그가 닫히지 않았습니다. `<head>` 태그를 닫아주세요.


## 최종 평가
위의 수정 사항들을 반영해주시면, 코드의 일관성과 유지보수성이 향상될 것입니다. 변경 사항을 반영해 주시면 PR을 승인하겠습니다. 감사합니다!

승인 상태: 수정 요청

2024-07-08 05:48 UTC, jaehwan-space commented
# PR 추가 리뷰

## 피드백
- title 태그의 내용을 `Component - Button`로 변경

2024-07-08 06:50 UTC, jaehwan-space requested changes
# PR 리뷰
## 요약
- 버튼 클래스 이름에 대해 primary, transparent 등을 사용하여 수정
- 버튼 컴포넌트 시안을 보면 배경색상이 하얀색이 아닌 투명으로 확인됨
- global.css에 기본 화이트 색상 변수가 있으므로 해당 변수를 사용

## 피드백
1. 버튼 클래스 이름 수정

    - 버튼 클래스 이름에 대해 포인트 컬러는 primary, 투명은 transparent 등을 사용해 주세요.
    - 예시:
      ```css
      .button--primary {
        /* 포인트 컬러 스타일 */
      }

      .button--transparent {
        /* 투명 스타일 */
      }
      ```
2. 버튼 배경색 수정

    - 버튼 컴포넌트 시안을 보면 배경색상이 하얀색이 아닌 투명으로 확인됩니다. 배경색을 투명으로 수정해 주세요.
    - 예시:
        ```css
        .button--transparent {
          background-color: transparent;
        }
        ```
3. global.css 색상 변수 사용

    - global.css에 기본 화이트 색상 변수가 있으므로 해당 변수를 사용해 주세요.

## 최종 평가
변경 사항을 반영해 주시면 PR을 승인하겠습니다. 감사합니다!

승인 상태: 수정 요청

2024-07-09 01:18 UTC, chlyun commented
# PR 리뷰
## 요약
-버튼의 폰트가 적용되고있지않음
-폰트의 굵기설정이 적용되고있지않음

## 피드백
1. 버튼 안쪽의 글자 폰트가 적용 되고있지않음
     - font-family: inherit; 설정
2. 폰트의 굵기설정이 적용되고있지않음
     - font-weight  설정



## 최종 평가
변경 사항을 반영해 주시면 PR을 승인하겠습니다. 감사합니다!
승인 상태: 수정 요청

2024-07-11 09:24 UTC, chlyun approved these changes
검토완료했습니다!

2024-07-11 14:41 UTC, jaehwan-space requested changes
# 코드 리뷰 (PR Review)
1. 버튼 컴포넌트의 width 변경 필요

    - 현재 버튼 컴포넌트의 세로 크기는 고정되어 있지만, 사용에 따라 너비가 달라질 수 있습니다. 따라서, 버튼의 width를 100%로 설정하는 것이 좋습니다. 이렇게 하면 버튼이 부모 컨테이너의 너비에 맞춰 자동으로 조정되어 다양한 레이아웃에서 유연하게 사용할 수 있습니다.
    ```css
    .button-large{
        width: 100%;
    }
    ```
2. 마우스 커서 hover 시 마우스 아이콘 모양 변경
    ```css
    cursor: pointer;
    ````
---
이러한 변경사항을 반영하시면 버튼 컴포넌트의 유연성과 재사용성이 향상될 것입니다.

감사합니다.

2024-07-12 06:00 UTC, jaehwan-space approved these changes
# 코드 리뷰 (PR Approve)
모든 수정사항 변경 확인했습니다.

2024-07-12 06:30 UTC, merged