Feat/component product
FRONTENDSCHOOL10/ssagwa-kurly pull request #27
Opened 2024-07-09 04:38 UTC by dabini99

## 🔧 반영 브랜치
---
feat/component-product-> develop

## 💬 Description
---
- [X] product 컴포넌트 구현
- [X] 할인률 계산 함수

## 📷 Screenshots
---
<img width="252" alt="스크린샷 2024-07-09 오후 1 30 33" src="https://github.com/FRONTENDSCHOOL10/ssagwa-kurly/assets/150096256/cd8761aa-4198-420d-b5ee-9403a8941cda">

Resolves #13

2024-07-11 16:01 UTC, jaehwan-space requested changes
# 코드 리뷰 (PR Review)
1. reset.css 링크 삭제

    - HTML 파일에서 reset.css를 링크하는 부분을 삭제해주세요. 이 스타일 시트는 global.css를 불러온다면 안에 포함되어 있으므로 제거하는 것이 좋습니다.

2. CSS 파일을 JS 파일에서 로드

    - product.css 파일을 JavaScript 파일에서 로드해주세요. 이렇게 하면 스타일을 모듈화하여 관리할 수 있습니다.
    ```javascript
    // js 파일
    import 'src/components/product/product.css';
    ```
3. 타이틀 명 변경

    - HTML 파일의 title을 `Components - Product`로 변경해주세요.

4. 할인율이 0%인 경우 고려

    - 할인율이 0%인 경우를 고려한 처리가 필요합니다. 현재 코드에서는 할인율이 0%일 때의 처리가 누락된 것 같습니다.


5. 배송 타입과 상품 제목 사이 여백 확인

    - 배송 타입과 상품 제목 사이의 여백이 디자인 시안과 달라보입니다. 확인 후 수정 부탁드립니다.

6. HTML 접근성 관련 수정

    - HTML 문법 검사 시 접근성 관련 부분을 수정해주세요.
    
    ![image](https://github.com/FRONTENDSCHOOL10/ssagwa-kurly/assets/32737360/59fe45ac-79e9-4df5-818f-b39229388245)

--- 
이러한 변경사항을 반영하시면 코드의 품질과 접근성이 크게 향상될 것입니다.

감사합니다.

2024-07-14 09:18 UTC, chlyun approved these changes
확인했습니다

2024-07-14 09:24 UTC, jaehwan-space requested changes
# 코드 리뷰 (PR Review)
1.  a 태그의 Scope 고려

    - 현재 `a`태그의 범위는 텍스트 요소들과 버튼을 함께 감싸고 있습니다. 이는 버튼을 누를 경우 버튼이 눌리지 않고 `a`태그가 작동되므로 수정이 필요합니다.


--- 

감사합니다.

2024-07-14 09:34 UTC, jaehwan-space approved these changes
# 코드 리뷰 (PR Approve)
모든 수정사항 변경 확인했습니다.

2024-07-14 09:35 UTC, merged