Feat: 장바구니 모달 컴포넌트 마크업/스타일링 구현
FRONTENDSCHOOL10/ssagwa-kurly pull request #34
Opened 2024-07-10 17:48 UTC by heydoopal

## 🔧 반영 브랜치

feat/component-cart-modal-> develop

## 💬 Description
- 마크업/스타일링 구현 
  - stepper, button 컴포넌트 develop 브랜치에 merge 한 후 해당 컴포넌트에 삽입 필요해요!
- 장바구니 모달 open/close 로직 
- 상품 데이터 임포트 로직 구현
- 아직 컴포넌트 / 함수 관련 JS는 미완상태

Related to #5

2024-07-11 16:45 UTC, jaehwan-space requested changes
# 코드 리뷰 (PR Review)

1. 디자인 시안과 `font-weight` 일치 여부 확인

    - 디자인 시안과 일치하지 않는 font-weight를 확인해야 합니다. 

2. CSS 및 JS 파일 로드 최적화 및 모듈 활용

    - CSS 및 JS 파일을 로드할 때 모듈 시스템을 활용하여 필요한 부분만 로드하도록 최적화해야 합니다. 이는 성능을 향상시키고 코드 관리를 용이하게 합니다.
    ```javascript
    // 예시: 모듈을 이용한 최적화 / 필요한 모듈만 로드하여 사용
    import 'src/components/cartModal/cartModal.css';
    import 'src/components/cartModal/data.js';
    ```
3. cartModal.css에서 사용한 * 선택자에 대한 리스크

    - cartModal.css에서 사용한 `*` 선택자는 모든 요소에 스타일을 적용할 수 있어서 컴포넌트 조립 시 다른 요소들에도 영향을 미칠 수 있습니다. 이는 추후에 문제가 될 수 있으므로 가능한 한 구체적인 선택자를 사용하거나 CSS 모듈화를 고려해야 합니다.

4. 전체적인 폴더 경로 변경에 따른 절대경로 수정

    - 전체적인 폴더 경로 변경에 따라 절대경로를 수정해야 합니다. 프로젝트 구조를 확인하고 필요한 파일들의 경로를 정확히 지정해야 합니다.
---
위의 사항들을 검토하고 수정하면 장바구니 모달 컴포넌트의 디자인 일치성과 성능 최적화가 개선될 것입니다.

감사합니다.

2024-07-11 17:17 UTC, heydoopal commented
혹시 피그마 디자인 시안과 꼭 100% 일치하게 작업해야 하나요 ? 
시안을 참고하여 다른 디자인으로도 꾸며도 된다고 알고있었어서요!
거의 대부분을 피그마 시안대로 작업하고 있으나, 시안과 실제 쇼핑몰에서 적용되어있는 부분이 상이한 부분이 있었고 
구현해봤을 때 조금 더 어울리는 폰트 두께나 약간의 마진은 조정하고 있었거든요!

2024-07-11 17:52 UTC, jaehwan-space commented
시안과 100% 일치하게 작업하지 않아도 된다는 의견에 저도 동의합니다!
다만 아래의 사진과 같이 상품 제목 부분의 글자 두께가 달라지면 더 강조되는 효과도 있고 시각적으로 느낌도 달라져서 제안드립니다.
  <img src="https://github.com/FRONTENDSCHOOL10/ssagwa-kurly/assets/32737360/876dbf07-1bd1-4821-8816-7e0999e01db7" width="50%"> 
  <img src="https://github.com/FRONTENDSCHOOL10/ssagwa-kurly/assets/32737360/30acf9d3-dc42-4ea4-83a0-2bcb555ca2fc" width="50%">

2024-07-12 04:55 UTC, heydoopal commented
앗! 저렇게 weight을 달리주니 제목이 더 강조가 되어서 좋은 것 같습니다! 👍  

그렇다면 제목에 font-weight을 더 주는게 좋다는 의견이신건가요!
리뷰에 시안과 다르게 작업해주셨다는 의견을 남겨주셔서요!
디자인 시안에는 모두 font-weight 600으로 되어있습니다!

2024-07-12 05:02 UTC, heydoopal commented
아아 제목에 강조를 주니 훨씬 더 좋은 것 같습니다! 👍

그럼 title에는 weight 값을 더 주는것이 좋다는 의견을 주신게 맞으실까요! 
figma시안에는 최종 금액 이외에 제목, 가격 등등 모두  600으로 되어있는데, (저는 모두 700으로 줬었네요!)
제목만 더 강조를 주는 걸로 수정하면 괜찮을까요 ㅎㅎ

2024-07-12 06:34 UTC, jaehwan-space commented
네네 그렇게 수정하면 좋을 것 같습니다! 
이외에도 유진님이 보시고 디자인적으로 더 괜찮을 것 같은 부분이 있다면 해당 부분도 수정 부탁드려요!

2024-07-12 07:16 UTC, heydoopal commented
리뷰 주신내용 모두 수정 후 push하였습니다! :D

2024-07-12 15:40 UTC, jaehwan-space approved these changes
# 코드 리뷰 (PR Approve)
모든 수정사항 변경 확인했습니다.

2024-07-12 15:57 UTC, merged